# Generated by Django 5.2.5 on 2025-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
