# Generated by Django 5.2.5 on 2025-08-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_app', '0002_message_message_id_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, help_text='معرّف الرسالة من واتساب (للتتبع فقط)', max_length=255, null=True, unique=True),
        ),
    ]
